# Load packages
library(shiny)
library(shinythemes)
library(tidyverse)

# Load data
sex_survey <- read_csv("/cloud/project/data/SexSurvey_tidy.csv")

# UI
ui <- fluidPage(theme = shinytheme("lumen"),
                titlePanel("Sexual Partners based on Demographic Factors"),
                sidebarLayout(
                  sidebarPanel(
                    
                    # major and student are not included as categorial variables to group by or color by
                    # because the entire dataset is filtered for student == 'Yes' and major had too many
                    # different values for the plot generated by this shiny app to be meaningful
                    
                    selectInput(inputId = "w", label = "Group X Axis By: ",
                                choices = c("gender", "year",
                                            "athlete", "greek", "politics", "religious", 
                                            "relationship"),
                                selected = "year"),
                    
                    selectInput(inputId = "y", label = "Y Axis: ",
                                choices = c("partners", "partners_college"),
                                selected = "partners_college"),
                    
                    selectInput(inputId = "z", label = "Color: ",
                                choices = c("gender", "year",
                                            "athlete", "greek", "politics", "religious",
                                            "relationship"),
                                selected = "gender")
                  ),
                  
                  # Output:
                  mainPanel(
                    plotOutput(outputId = "barplot")
                  )
                )
)

server <- function(input, output) {
  
  # source for fuction below
  # https://stackoverflow.com/questions/48673842/using-shiny-interactive-input-to-filter-na-values-not-working
  
  output$barplot <- renderPlot({
    sex_survey %>%
      filter_(sprintf("!is.na(%s)", input$w)) %>%
      filter_(sprintf("!is.na(%s)", input$y)) %>%
      filter_(sprintf("!is.na(%s)", input$z)) %>%
      filter(student == "Yes") %>%
      mutate(year = factor(year, c("Freshman", "Sophomore", "Junior", "Senior")))%>%
      group_by(input$w) %>%
      ggplot(aes_string(x = input$w, y = input$y, fill = input$z)) +
      geom_bar(stat = "summary", position = "dodge", fun.y = "mean") +
      theme_bw()
  })
}

shinyApp(ui = ui, server = server)
  